---
title: Wiki
number-sections: true
---

## Installation{#sec-wiki-installation}

### Install Julia
- Install Julia using instructions from [here](https://julialang.org/downloads/)

### Download Repository & Setup Environment
- Clone this repository using `git clone https://git.rwth-aachen.de/mbd_teaching/internship-tj.git`
- Change directory to cloned folder
- Setup the Environment using `julia setup.jl`

### Install Quarto
For pre-release version (here 1.5.39) of Quarto:
```
export QUARTO_VERSION=1.5.39
sudo mkdir -p /opt/quarto/${QUARTO_VERSION}
sudo curl -o quarto.tar.gz -L "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.tar.gz"
sudo tar -zxvf quarto.tar.gz -C "/opt/quarto/${QUARTO_VERSION}" --strip-components=1
sudo ln -s /opt/quarto/${QUARTO_VERSION}/bin/quarto /usr/local/bin/quarto
quarto install tinytex
quarto check
```

## Documentation

We recommend using VS-Code with the Quarto extension installed for any technical writing. Especially in the [*Quarto Visual Mode*](https://quarto.org/docs/visual-editor/vscode/)*,* inserting figures/tables/references works like a charm.
Add your content in the `docs/report` section. Feel free to add new `*.ipynb` or `*.qmd` files. Make sure to add there files into the `_quarto-public.yml` and/or `_quarto-private.yml` to be renderes on the public/private website beloning to this project.

## Presentation

There is a basic quarto template located in `docs/presentation`.

## Adding a new file to the webpage

We have two versions of the website. A private and a public one. The configuration can be found in `_quarto-private.yml` and `quarto-public.yml` respectively. 
Open the corresponding file and add the path to the new file in the `sidebar` section.

## Rebuilding the website
The website is rebuild automatically after a new pushed commit to the main-branch of the project.

## Testing the full page locally:
### Debian/Ubuntu
Run the `scripts/build.sh` shell script.

::: {.callout-warning}
The script is used in the gitlab-ci to build the website. If you change the script, you might break the automatic building of the webpage.
:::

### Other OS:
The following commands are based on the shell commands on Debian/Ubuntu. You need to use the corresponding commands for your OS.
If you use a different OS, please contribute your workflow in a script `build_<OS>.sh`, where you replace `<OS>` with the OS you are using.

Build the private/public webpage via
```
quarto render --profile public
```
or 
```
quarto render --profile private
```
Now build the presentation, if you want it to be included:
```
cd docs/presentation
quarto render
cd ../..
```
Now copy paste the presentation into the public/private output folder, if you want to enable thel link *presentation*:
```
cd _output-public
cp -r ../_output_presentation .
cd ..
```
or
```
cd _output-private
cp -r ../_output_presentation .
cd ..
```
Lastly, copy the public webpage content into the private folder, if you want to enable the link *public website*:
```
cd _output-private
cp -r ../_output-public .
cd ..
```

## FAQ: 

