# Changes here will be overwritten by Copier
AddPrecommitUpdateCI: false
Authors: Tanish Jain, Alan Correa
JuliaMinVersion: '1.12'
License: MIT
LicenseCopyrightHolders: Tanish Jain, Alan Correa
PackageName: GlissADe
PackageOwner: thealanjason
PackageUUID: d94f865e-9be7-4415-9b4a-0e34ca8c7922
StrategyConfirmIncluded: false
StrategyLevel: 3
StrategyReviewExcluded: false
_commit: v0.18.6
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
