variables:
  ACCESS_TOKEN: __
  BASE_IMAGE: ubuntu:latest
  QUARTO_VERSION: 1.5.39
image: $BASE_IMAGE

stages:
  - build_all_and_deploy_private_version
  # - deploy_public_version
  

pages:
  stage: build_all_and_deploy_private_version

  before_script:
    - apt-get update -qq
    - apt-get install curl -y
    - echo "install julia"
    - curl -fsSL https://install.julialang.org | sh -s -- -y 
    - echo "install quarto"
    - mkdir -p /opt/quarto/${QUARTO_VERSION}
    - curl -o quarto.tar.gz -L "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.tar.gz"
    - tar -zxvf quarto.tar.gz -C "/opt/quarto/${QUARTO_VERSION}" --strip-components=1
    - ln -s /opt/quarto/${QUARTO_VERSION}/bin/quarto /usr/local/bin/quarto
    - quarto install tinytex
    - echo "check quarto installation"
    - quarto check
    - quarto --version
  script:
    - echo "build quarto pages"
    - cd ./scripts
    - bash ./install.sh
    - bash ./build.sh
    - cd ..
    - ls -la -tr
    - rm -rf public
    - mv _output-private public
    - ls public/ -la -tr
  artifacts:
    paths:
      - public/
      - _output-public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


# deploy-public:      
#   stage: deploy_public_version
#   dependencies:
#     - pages
#   before_script:
#     - echo "Setup Git"
#     - apt-get update -qq
#     - apt-get install git -y
#     - git config --global user.name MBD-CI-BOT
#     - git config --global user.email cibot@mbd.rwth-aachen.de
  
#   script:
#     - echo "Publishing rendered website to public repository.."
#     - git clone https://oauth2:$ACCESS_TOKEN@git.rwth-aachen.de/mbd_student/projects.git
#     - mv _output-public $CI_PROJECT_NAME
#     - cd projects/projects
#     - rm -rf $CI_PROJECT_NAME
#     - mv ../../$CI_PROJECT_NAME .
#     - git add -A  
#     - git commit -m "Update Website"
#     - git push --force
#     - echo "Publishing complete"

#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     - when: manual


