project:
  output-dir: _output-public
engine: julia

website:
  navbar:
    left:
      - text: "Documentation"
        file: _docs/report/00_intro.qmd
  sidebar: 
    - id: documentation
      title: "Documentation"
      contents:
        - _docs/report/00_intro.qmd
        - _docs/report/implementation/implementation.qmd
        - _docs/report/tutorial/tutorial.qmd
        - _docs/report/API/API.qmd
        - _docs/report/30_appendix.qmd
        - _docs/report/40_references.qmd





