project:
  output-dir: _output-private
engine: julia

website:
  navbar:
    left:
      - text: "Organization"
        file: _docs/orga/organization.qmd
      - text: "Documentation"
        file: _docs/report/00_intro.qmd
      - text: "Presentation"
        file: _output-presentation/presentation.html
      - text: "Wiki"
        file: _docs/wiki/index.qmd
      - text: "Public Website"
        file: _output-public/index.html
  sidebar:
    - id: documentation
      title: "Documentation"
      contents:
        - _docs/report/00_intro.qmd
        - _docs/report/implementation/implementation.qmd
        - _docs/report/tutorial/tutorial.qmd
        - _docs/report/API/API.qmd
        - _docs/report/30_appendix.qmd
        - _docs/report/40_references.qmd
    - id: organization
      title: "Organization"
      contents:
        - _docs/orga/organization.qmd
        - _docs/orga/milestones.qmd
        - _docs/orga/tasklist.qmd
        - _docs/orga/meeting1.qmd
    - id: wiki
      title: "Wiki"
      contents:
        - _docs/wiki/index.qmd
