name = "GlissADe"
uuid = "c62e89b2-53d1-54ab-a70e-4de435161310"
authors = [
    "Tanish Jain <recklurker@gmail.com>",
    " Alan Correa <correa@mbd.rwth-aachen.de>",
]
version = "0.1.0"

[workspace]
projects = ["test", "docs"]

[compat]
julia = "lts"
