#=
# Mesh Utils.
# Copyright (c) 2025 Tanish Jain.
# Licensed under the MIT license.
=#
export meshbounds

"""
    _neighbours(l, faces)
Computes the neighbours of all faces in the mesh. This algorithm has a time complexity of ``O(PE)`` where 
``P, E`` are the total number of points and edges in the mesh respectively.
## Arguments
- l = ``P``, Total number of points in the mesh
- faces - Vector containing information of all the faces in the mesh
"""
function _neighbours(l, faces)
    t_start = time()
    point_face_map = [Vector{INT_TYPE[]}() for _ in 1:l]
    STATS[] && println("Computing point face map...")
    if Threads.nthreads == 1 || !THREADS[]
        for i in 1:l # Reduce Threads overhead
            @inbounds for j in eachindex(faces)
                if i in faces[j]
                    push!(point_face_map[i], j)
                end
            end
        end
    else
        @inbounds Threads.@threads for k in 1:(l * length(faces) - 1)
            i = k ÷ length(faces) + 1
            j = (k - 1) % length(faces) + 1
            if i in faces[j]
                push!(point_face_map[i], j)
            end
        end
    end
    t1 = time()
    STATS[] && println("Computing point face map took: ", t1 - t_start, " seconds") # Status Update
    neighbours = [Vector{INT_TYPE[]}() for _ in eachindex(faces)]
    @inbounds @maybe_threads Threads.nthreads == 1 || !THREADS[] for j in eachindex(faces)
        count = 0
        @inbounds for v in eachindex(faces[j])
            e = (v) % length(faces[j]) + 1
            set_v = Set(point_face_map[faces[j][v]])
            set_e = Set(point_face_map[faces[j][e]])
            neighbour = intersect(set_v, set_e)
            if neighbour == Set([j])
                push!(neighbours[j], -count)
                count += 1
            else
                c = [neighbour...]
                n = (c[1] == j) ? c[2] : c[1]
                push!(neighbours[j], n)
            end
        end
    end
    STATS[] && println("Computing neighbours took: ", time() - t1, " seconds")
    return neighbours
end

"""
    meshbounds(points)
Computes the mesh span on the ``xy`` plane of mesh vertices. 

## Arguments 
- points - Coordinates of all vertices of a mesh. 
"""
function meshbounds(points::Vector{Vector{T}}) where {T <: Real}
    @inbounds x_min = points[1][1]
    @inbounds x_max = points[1][1]
    @inbounds y_min = points[1][2]
    @inbounds y_max = points[1][2]
    @inbounds for i in eachindex(points)
        x = points[i][1]
        y = points[i][2]
        x_min = min(x_min, x)
        y_min = min(y_min, y)
        x_max = max(x_max, x)
        y_max = max(y_max, y)
    end
    println("x_min: ", x_min, ", x_max: ", Real(x_max))
    return println("y_min: ", y_min, ", y_max: ", Real(y_max))
end

"""
    meshbounds(Cells) 
Computes the mesh span on the ``xy`` plane of mesh cell centroids.
See also: [`preprocess`](@ref)
## Arguments 
- Cells::Vector{Cell{T,S,W}} - Cell structure generated by `preprocess`
"""
function meshbounds(Cells)
    x_min = Cells[1].center[1]
    x_max = Cells[1].center[1]
    y_min = Cells[1].center[2]
    y_max = Cells[1].center[2]
    @inbounds for i in eachindex(Cells)
        x = Cells[i].center[1]
        y = Cells[i].center[2]
        x_min = min(x_min, x)
        x_max = max(x_max, x)
        y_min = min(y_min, y)
        y_max = max(y_max, y)
    end

    println("x_min: ", x_min, " x_max: ", x_max)
    return println("y_min: ", y_min, " y_max: ", y_max)
end

## Compute Average Spacing between cells ##

"""
Multithreading auxillary for computeMeanDelta
"""
function _sum_meandelta(Cells, chunk)
    T = eltype(Cells[1].center)
    s = zero(T)
    for i in chunk
        @inbounds for j in eachindex(Cells[i].neighbours)
            n = Cells[i].neighbours[j]
            (n <= 0) && continue
            s += magnitude(Cells[i].center, Cells[n].center)
        end
    end
    return s
end

"""
Multithreading auxillary for computeMeanDelta
"""
function _sum_edges(Cells, chunk)
    global INT_TYPE
    count = zero(INT_TYPE[])
    for i in chunk
        @inbounds for j in eachindex(Cells[i].neighbours)
            n = Cells[i].neighbours[j]
            (n <= zero(INT_TYPE[])) && continue
            count += one(INT_TYPE[])
        end
    end
    return count
end

"""
    computeMeanDelta(Cells)
Computes mean spacing between face centroids. Uses multiple threads if `threads=true`. 
"""
function _mean_delta(Cells)
    global threads, INT_TYPE
    T = eltype(Cells[1].center)
    if (Threads.nthreads() == 1) || !threads
        Δₑ = zero(T)
        count = zero(INT_TYPE[])
        @inbounds for i in eachindex(Cells)
            @inbounds for j in eachindex(Cells[i].neighbours)
                (Cells[i].neighbours[j] <= 0) && continue
                n = Cells[i].neighbours[j]
                Δₑ += magnitude(Cells[i].center, Cells[n].center)
                count += 1
            end
        end
    else
        chunks = Iterators.partition(eachindex(Cells), div(length(Cells), Threads.nthreads()))
        tasks = map(chunks) do chunk
            Threads.@spawn sum_meandelta(Cells, chunk)
        end
        Δₑ = mapreduce(fetch, +, tasks, init = zero(T))
        tasks1 = map(chunks) do chunk
            Threads.@spawn sum_edges(Cells, chunk)
        end
        count = mapreduce(fetch, +, tasks1, init = zero(INT_TYPE[]))
    end
    return Δₑ / count
end
