#=
Responsible for parsing vertices in "points.txt" file generated by OpenFOAM.

Last Updated On: 11th January, 2025 20:37 UTC+5:30
=#

export parsepoints

"""
            parsepoints(location_points::String)
Parse the points file generated in an OpenFoam format and stores the coordinates in `FLOAT_TYPE` format. 

## Arguments 
- location_points::String - Location of the "points" file generated by OpenFOAM avalanche module
"""
function parsepoints(location_points::String)

    ## GET GLOBAL VARIABLES ##
    global FLOAT_TYPE, INT_TYPE, threads, stats

    # Read file
    f_point_cloud = open(location_points, "r")
    s_points_file = split(read(f_point_cloud, String), '\n')
    close(f_point_cloud)

    # [Advice on Stack] Only use Regex if you have to!
    total_points = parse(INT_TYPE[], s_points_file[20])
    s_points_cloud = @view s_points_file[22:(22 + total_points - 1)]

    # Process the string
    stats && println("Reading point cloud...")
    mesh_points = Vector{Vector{FLOAT_TYPE[]}}(undef, length(s_points_cloud)) # Preallocating for speed
    @inbounds @maybe_threads Threads.nthreads == 1 || !threads for i in eachindex(s_points_cloud)
        s = split(strip(s_points_cloud[i], ('(', ')')))
        mesh_points[i] = [parse(FLOAT_TYPE[], s[1]), parse(FLOAT_TYPE[], s[2]), parse(FLOAT_TYPE[], s[3])] # always of appropriate size
    end
    return mesh_points
end
