# To Parse Faces from OpenFOAM formatted .txt files 
# Depend on utils/additionals.jl 

export parsefaces

"""
    parsefaces(location_faces::String)
Parse the connectivity list of a mesh in an OpenFOAM format and store it in type `INT_TYPE`

## Arguments 
- location_faces::String - Location of the "faces" file generated by OpenFOAM avalanche module
"""
function parsefaces(location_faces::String)
    global INT_TYPE, stats, threads

    # Read file line by line
    total_faces = 0
    s_faces_arr = String[]

    open(location_faces, "r") do f_faces
        for (i, line) in enumerate(eachline(f_faces)) 
            if i == 20
                total_faces = parse(INT_TYPE[], line)
            elseif i >= 22 
                !is_valid_face_line(line) && continue 
                push!(s_faces_arr, line)
            end
        end
    end
    # Process the string
    stats && println("Reading face information...")
    mesh_faces = Vector{Vector{INT_TYPE[]}}(undef, length(s_faces_arr))
    @inbounds @maybe_threads Threads.nthreads() ==1 || !threads for i in eachindex(s_faces_arr)
        line = s_faces_arr[i]
        parts = split(line, '(')
        # n = parse(Int, strip(parts[1]))  # Number of points in the face Check: Length(numbers) == n. Not required, In Openfoam we trust!
        numbers_str = strip(parts[2], [' ', ')'])  # Remove Trailing Parenthesis
        numbers = split(numbers_str, " ")
        mesh_faces[i] = parse.(INT_TYPE[], numbers) .+ 1  # Convert to 1-based indexing
    end
    return mesh_faces, INT_TYPE[](length(mesh_faces) - total_faces)
end
