# To parse "faceLabels" files generated by OpenFOAM in .txt files. 

export parsefacelabels

"""
    parsefacelabels(location_faceLabels::String, correction_factor)
Parse indices of the faces forming the terrain in a text file with OpenFoam format and stores it in `INT_TYPE`

## Arguments 
- location_faceLabels::String
- correction_factor::INT_TYPE - To account for the corrections in the text file (where the parser skipped because of invalid syntax)
"""
function parsefacelabels(location_faceLabels::String, correction_factor)
    global INT_TYPE, threads, stats

    # Open file and skip header lines directly
    f_surface_aligned_faces = open(location_faceLabels, "r")
    for _ in 1:19
        readline(f_surface_aligned_faces)
    end

    total_surface_aligned_faces = parse(INT_TYPE[], readline(f_surface_aligned_faces))
    idx_surface_aligned_faces = Vector{INT_TYPE[]}(undef, total_surface_aligned_faces) # Preallocating for speed
    readline(f_surface_aligned_faces) # Opening parenthesis
    # Read and parse face labels
    stats && println("Reading face labels...")
    s_surface_aligned_faces_arr = Vector{String}(undef, total_surface_aligned_faces)
    @inbounds for i in 1:total_surface_aligned_faces
        s_surface_aligned_faces_arr[i] = readline(f_surface_aligned_faces)
    end
    close(f_surface_aligned_faces)

    @inbounds @maybe_threads Threads.nthreads() == 1 || !threads for i in 1:total_surface_aligned_faces
        idx_surface_aligned_faces[i] = parse(INT_TYPE[], s_surface_aligned_faces_arr[i]) + 1 + correction_factor
    end
    return idx_surface_aligned_faces
end

