using GlissADe

## HOW TO RUN THIS FILE? ##
# From the project root: julia --project examples/plane_sample/plane.jl

## What does this file do? ##
# This file can be used to check manually whether the geometrical information computed is correct on a sample
# inclined plane with 9 faces in addition to showcasing the library's compatibility with differentiation with the geometry
# of the mesh (the coords of all vertices of the mesh).

init(threads = true, stats = true, plots = false, int_type = Int64) # Initialize the library

# Parse the mesh generated by OpenFOAM's polyMesh and makeFaMesh with ASCII files available at this locations.
points, faces = parsemesh(
    "./examples/plane_sample/plane/points",
    "./examples/plane_sample/plane/faces",
    "./examples/plane_sample/plane/faceLabels",
)
Cells = preprocess(points, faces, Float64, comp_neighbours = true) # Precompute geometrical information.
# If comp_neighbours=true, neighbours will be recomputed even if already stored.

## WARNING. only a simple compatbility check is performed to ensure that the stored neighbour file is for the current mesh.
## Use comp_neighbours=false, only if the file is correct.

# Check Sparsity pattern of implicit matrix (after reordering) [Can use spy(A)]#
neighbours = [Cell.neighbours for Cell in Cells]
A = GlissADe.adjMatrix(neighbours) # internal helper, not exported
##

# Set up release area
meshbounds(Cells) # Find the span of the mesh.

## Check Geometrical Computations. Cell.area, Cell.normal, etc.


## AUTOMATIC DIFFERENTIATION ##

## Differentiate geometrical information w.r.t. vertices of the mesh. ##
import ForwardDiff
function testDifferentiability(x)
    global points, faces
    points_diff = [x[(3*i-2):(3*i)] for i in eachindex(points)]
    Cells = preprocess(points_diff, faces, eltype(x), comp_neighbours = false)
    areas = [Cell.area for Cell in Cells]
    return areas
end
ppoints = [Iterators.flatten(points)...]
jac = ForwardDiff.jacobian(testDifferentiability, ppoints)
