#=
The PRECOMPUTATIONS submodule is resposible for the logic of parsing the mesh, precomputing 
local geometrical information of the mesh, and reordering the mesh into a "cache-access" friendly numbering.

Last Updated On: 11th January, 2025 21:05 UTC+5:30
=#

"""
    parsemesh(location_points::String, location_faces::String, location_faceLabels::String)
Parse the files of a mesh in OpenFoam format.
See also [`parsepoints`](@ref), [`parsefaces`](@ref), [`parsefacelabels`](@ref)
    
- location_points::String - Location of "points" file generated by OpenFOAM polymesh. 
- location_faces::String - Location of "faces" file generated by OpenFOAM polymesh.
This is an internal function and should not be exposed to the user.
"""
function parsemesh(location_points::String, location_faces::String, location_faceLabels::String)
    global FLOAT_TYPE, INT_TYPE, threads, stats 
    stats && println("Using ", Threads.nthreads(), " threads")
    mesh_points = parsepoints(location_points)
    mesh_faces, corr_factor = parsefaces(location_faces) # Correction Factor, dev fix, don't change!
    idx_faces = parsefacelabels(location_faceLabels, corr_factor)
    surface_aligned_faces = deepcopy(mesh_faces[idx_faces]) 

    # Get points on the surface
    @inbounds surface_points_idx = [x[j] for x in surface_aligned_faces for j in eachindex(x)] # Get points on the surface aligned mesh  
    unique!(surface_points_idx) # Remove repeated indcies
    sort!(surface_points_idx) # Sort the indices, prepare for remapping 
    
    # Remapping of surface points in 1:N
    global_surface_idx_map = Dict(surface_points_idx .=> 1:length(surface_points_idx)) # New Index ReMap
    surface_aligned_faces_remapped = Vector{Vector{INT_TYPE[]}}(undef, length(surface_aligned_faces))
    @inbounds surface_points = mesh_points[surface_points_idx]
    
    @inbounds @maybe_threads Threads.nthreads==1 || !threads for i in eachindex(surface_aligned_faces)
            l = length(surface_aligned_faces[i])
            surface_aligned_faces_remapped[i] = [global_surface_idx_map[j] for j in surface_aligned_faces[i]]
    end
    return surface_points, surface_aligned_faces_remapped
end

"""
    meshcomputations(points, faces, neighbours, mesh)
Precompute geometrical information of a parsed mesh and store it in the `Cell` structure
    
- `points` - Array containing vertices of the mesh
- `faces` - Array containing connectivities/faces of the mesh
- `neighbours` - Array containing neighbours of each face of the mesh
```
"""
function meshcomputations(points, faces, neighbours, W) 
    global threads, stats, INT_TYPE
    face_normals_centroids = normals(points, faces)
    @inbounds cell_centroids = [p[1] for p in face_normals_centroids]
    @inbounds cell_normals = [p[2] for p in face_normals_centroids] # Negative to align with gravity
    edgecenters = edge_centers(points, faces) # Edge Centers 

    areas = computeAreas(points, faces, cell_centroids) # Surface Area of each face 
    edgelengths = edge_lengths(points, faces) # Edge Lengths of each edge of a face 
    
    binormal_transform = binormal_transforms(cell_centroids, edgecenters, cell_normals, points, faces, neighbours)
    @inbounds binormals = binormal_transform[1]
    @inbounds transforms = binormal_transform[2]
    @inbounds transforms2 = binormal_transform[3]

    # Construct Mesh Cells [Initialize to Zero]
    T = eltype(points[1])
    Cells = Vector{Cell{T, INT_TYPE[], W}}(undef, length(faces))
    @inbounds @maybe_threads Threads.nthreads==1 || !threads for i in eachindex(faces)
        Cells[i] = Cell{T, INT_TYPE[], W}(i, cell_centroids[i], points[faces[i]], edgecenters[i], edgelengths[i], 
                                cell_normals[i], areas[i], binormals[i], transforms[i], transforms2[i], neighbours[i], zero(W), zeros(W,3), zero(W))
    end
    return Cells
end

"""
    preprocess(points, faces; comp_neighbours=true)
Precompute geometrical information and store it in the `Cell` structure. 

- `points` - coordinates of the vertices of the mesh. 
- `faces` - connectivity list of the mesh. 
- `W` - Datatype to be used for variables. Should be of type `Dual` if differentiating with geometry
- `comp_neighbours` - Whether to compute neighbours or read from file. Default is `true`. In case of incompatibility with mesh, neighbours will be recomputed.
"""
function preprocess(points, faces, W; comp_neighbours = true)
    global stats 

    # Read from file if it exists. 
    if !comp_neighbours
        if isfile("./stored/neighbours.jld2") 
            neighbours = load_object("./stored/neighbours.jld2")
            # If the neighbour list is incompatible with the given geometry, recompute neighbours
            if(length(neighbours) != length(faces)) 
                comp_neighbours = true 
            end
            stats && println("Neighbours read from file at /stored/neighbours.jld2")
        else 
            comp_neighbours = true 
        end
    end

    # Compute Neighbours
    if comp_neighbours 
        if !Base.isdir("./stored")
            mkdir("./stored")
        else 
            Base.rm("./stored", recursive=true)
            Base.mkdir("./stored")
        end
        neighbours = computeneighbours(length(points), faces)
        save_object("./stored/neighbours.jld2", neighbours)
        stats && println("Neighbours computed and stored at /stored/neighbours.jld2")
    end

    # Reordering of mesh - Enables faster cache accesses
    stats && println("Reordering mesh....")
    A = adjMatrix(neighbours)
    ph = RCM(A)
    faces .= @view faces[ph]
    neighbours .= @view neighbours[ph]
    reordering = Dict(ph .=> 1:length(faces))
    @inbounds for i in eachindex(neighbours)
            @inbounds for j in eachindex(neighbours[i])
                neighbours[i][j] <= 0 && continue 
                neighbours[i][j] = reordering[neighbours[i][j]]
            end
    end
    Cells = meshcomputations(points, faces, neighbours, W)
    return Cells
end
