---
title: "Tutorial"
engine: tex

execute:
  freeze: auto
---

*First steps are always small*

It is hoped but not guranteed, to make this library as user-friendly as possible. Here's a walkthrough of how to perform a simulation using this library. 

# Mesh definition and precomputations 
The library was built up to provide differentiability for a specific use-case: Sensitivity analyses of Avalanches w.r.t. topography, initial conditions and model parameters. As such, OpenFoam offers support for generating finite area meshes or surface-discretizations. Thus, the library requires the mesh to be in OpenFoam's format. For general support with any 3D model, please generate the mesh using OpenFoam's [avalanche](https://develop.openfoam.com/Community/avalanche) module. Once the files are generated, look into `constant\polyMesh` and `constant\faMesh` for the files `points`, `faces` and `faceLabels` files. Once that's done, here's how you should proceed. 

- Import the library. 
```julia
import FASolverAvalanche as FAS
```

- Next, define how the computations should be performed and initialize the library. 
```julia
process = FAS.Process(
            threads = true, 
            stats = true,
            plots = false,  
            INT_TYPE = Int64
)
FAS.init(process) # Initialize the library  
```

Setting `threads=true` allows the library to use multiple threads if available. `stats=true` will print intermediate state information and also acts as a progress bar. `plots=true` will enable side by side plotting while the solver is running. `INT_TYPE` defines the type used for integers throughout. Finally, the `init` function takes this as input and sets up the simulation process: Starting Pyplot backend for side by side plotting, etc. 

After that, parse the mesh and precompute geometrical information: 
```julia
points, faces = FAS.parsemesh("./examples/simpleslope/simpleslope/points", "./examples/simpleslope/simpleslope/faces", 
                                "./examples/simpleslope/simpleslope/faceLabels")
Cells = FAS.preprocess(points, faces, Float64, comp_neighbours=true) # Precompute geometrical information. 
# If comp_neighbours=true, neighbours will be recomputed even if already stored. 
```

# Defining Initial and boundary conditions
The free surface flow equations of the Savage Hutter model typically don't require boundary conditions. To handle the boundary, the solver uses a zero-gradient (Neumann) schemes. User-defined boundary conditions are not yet supported. Boundary conditions can help simulate inflow and outflow. Zero-gradient being the easiest to realize in code was chosen to represent the boundary. The solver is therefore currently limited to flows without external inflow and outflow. Initial conditions are given using a polygonal release area. Spherical release areas are not directly supported. But, remeber, a polygonal with infinite vertices approaches a circle :) Here's how initial conditions are defined: 

```julia
FAS.meshBounds(cells)
FAS.meshBounds(vertices)
polygon = FAS.findRegularPolygon([5.0, 10.0, -3.0,3.0], npoints=6)
cells_inside = FAS.cellsInsideBoundingPolygon(polygon, Cells)
FAS.initializeGeometry(cells_inside, Cells, rho, 
                        h0 = 0.5, u0 = [0.0,0.0,0.0] )
```

The `meshBounds` function gives the bounding region of the surface, i.e., the limits of **x** and **y** coodinates when the surfaces is projected onto the **xy** plane. This information can be used to assign different initial conditions in different parts of the mesh. The function `findRegularPolygon` finds a regular polygon inside a given rectangular region defined using ``[x_min, x_max, y_min, y_max]``. The supporting function `cellsInsideBoundingPolygon` finds all cells which lie inside the polygon. This is then passed to the `initializeGeometry` function which assigns the given value for thickness **h** and velocity vector **u** (in global coordinates) as specified. For a composure of initial conditions, it is possible to have multiple bounding polygons with different intial conditons like: 

```julia 
polygon1 = FAS.findRegularPolygon()
polygon2 = FAS.findRegularPolygon()
cells_inside1 = FAS.cellsInsideBoundingPolygon(polygon1, Cells)
cells_inside2 = FAS.cellsInsideBoundingPolygon(polygon2, Cells)
``` 
For even more complex initial conditions, it is also possible to iterate over the `Cells` vector directly. 
```julia
for i in eachindex(Cells)
    Cells[i].h = h_initial[i] # h_initial is defined before hand
    Cells[i].vel = vel_initial[i] # vel_initial is defined before hand
end
```

If the initial polygons intersect, the maximum of all the values will be chosen as the value at the cell. 

```julia
# First Polygon
polygon1 = FAS.findRegularPolygon([5.0, 10.0, -3.0,3.0], npoints=6)
cells_inside = FAS.cellsInsideBoundingPolygon(polygon1, Cells)
FAS.initializeGeometry(cells_inside, Cells, rho, 
                        h0 = 0.5, vel0 = [0.0,0.0,0.0] )
# Second Polygon 
polygon2 = FAS.findRegularPolygon([15.0,10.0,-5.0,15.0], npoints=5)
cells_inside = FAS.cellsInsideBoundingPolygon(polygon2, Cells)
FAS.initializeGeometry(cells_inside, Cells, rho, 
                            h0 = 0.3, vel0 = [0.0,0.0,1e-2]) # Different boundary conditions
```


> **_NOTE:_** Choose the initial polygon properly. If the polygon is too big, the solver might require some stabilization by appropriate choice of parameters. This however is not straightforward and might take several iterations to figure out. 

# Setting up the solver and final solution process
Once the initial conditions are set up, setting up the solver is simple. Create a structure `Solution` and pass it to the `Solver` function to create a `solver` object. The `solver` object contains the precomputed geometry and user choices for controlling the solution (relaxation factors, linear solvers, preconditioners, tolerances, etc.)
Here's an example,

```julia

solution = FAS.Solution(
    alpha = 0.5, # Coefficient for pressure terms
    zeta = 1.25, # Coefficient for momentum terms 
    rho = 1500.0, # Material density 
    alpha_p = 0.5, # Under relaxation for pressure. 
    alpha_u = 0.5,  # Under relaxation for velocity
    alpha_h = 0.5,  # Under relaxation for thickness.
    p_MAX_RESIDUAL = 1e-4, # Maximum allowed residual for pressure constraint. 
    h_MAX_RESIDUAL = 5e-1, # Maximum allowed residual for thickness equation. 
    u_MAX_RESIDUAL = 5e-1, # Maximum allowed residual for momentum equation. 
    MAX_ITERS = 150, # Maximum Iterations per timestep. 
    MIN_ITERS = 100, # Minimum iterations per timestep. 
    h_clip = 0.0, # Clip the thickness to 0 if h < h_clip
    h_min = 1e-3, # Minimum height to be considered wet. 
    Cells = Cells, # Precomputed geometry and initial conditions
    location = "./solution", # Folder to store the intermediate VTK files. Only formats with "./{name}" are allowed at present. 
    points = points,  # Vertices of the mesh
    faces = faces # Connectivity list of the mesh 
)
```

Once this is done, creating a solver is straightforward.

```julia
solver = FAS.Solver(solution)
```

Finally, it's time for solution. The `solve` function takes in the `solver` and starts the iteration process. Here's how the solve function should be used:
```julia
solver = FAS.Solver(solution) # Construct Solver object 
time_steps, sol= FAS.solve(solver, (0.0,30.0),saveat=0.2,Cₘ=0.9) # SIMULATE!
FAS.writeToVTK(solution.location, sol, points, faces) # Write the solution to VTK. Smoothens the intermediates to get accurate solutions. 
FAS.resetCells(Cells) # Reset all cells to 0 thickness and velocity. 
```

The second argument to the `solve` function is the tspan denoting the time the flow should be simulated. The function uses adaptive timestepping based on the Courant number to solve the equations. To have the solution saved at uniform timesteps, use the `saveat` argument denoting the uniform timestep, the solution needs to be saved at. The optional parameter `Cₘ` defines the maximum Courant number and can be used to control step-sizes for timestepping. 

# Post-processing
The library writes the solution at intermediate timesteps to VTK files. Using the `writeToVTK` function, a uniform time-step solution is generated and the intermediates are removed. 
```julia
FAS.writeToVTK("./solution/", sol, points, faces)
```
> **_NOTE:_** To avoid overwritting issues, the `writeToVTK` function deletes the contents of the given directory and then saves the new VTK files. It is recommended to create an empty directory for saving the solution to avoid losing other files.

And that's it. You solved the free surface flow equations and simulated avalanches on your geometry!

# Differentiation
To compute the derivatives using automatic derivatives is straightforward. Just wrap the logic defined above inside a function. Here is for example differentiation w.r.t. initial conditions. Make sure that ForwardDiff.jl allows only a single argument in form of arrays. The logic should be modified to ensure that. 

```julia
function testDifferentiabilityInitialConditions(x)
  process = FAS.Process(
            threads = true, 
            stats = true,
            plots = false,  
            INT_TYPE = Int64 
  )
FAS.init(process)
  points, faces = FAS.parsemesh("./examples/simpleslope/simpleslope/points", "./examples/simpleslope/simpleslope/faces", 
                      "./examples/simpleslope/simpleslope/faceLabels")
  Cells = FAS.preprocess(points, faces, eltype(x), comp_neighbours=false)
  FAS.meshbounds(Cells)
  polygon = FAS.findRegularPolygon([5.0,10.0,-6.0,6.0], npoints=6)
  cells_inside = FAS.cellsInsideBoundingPolygon(polygon, Cells)
  FAS.initializeGeometry(cells_inside, Cells, 1500.0, h0 = x[1], u0 = [0.0,0.0,0.0])
  solution = FAS.Solution(
    alpha = 0.5, 
    zeta = 1.25, 
    rho = 1500.0, 
    alpha_p = 0.5,  
    alpha_u = 0.5,  
    alpha_h = 0.5,  
    p_MAX_RESIDUAL = 1e-4, 
    h_MAX_RESIDUAL = 5e-1,  
    u_MAX_RESIDUAL = 5e-1,  
    MAX_ITERS = 60, 
    MIN_ITERS = 50,  
    h_clip = 0.0,  
    h_min = 1e-3,  
    Cells = Cells,  
    location = "./solution", 
    points = points,  
    faces = faces
  )
  solver = FAS.Solver(solution)
  time_steps, sol = FAS.solve(solver, (0.0,15.0),saveat=0.2,Cₘ=0.9)
  FAS.writeToVTK(solution.location, sol, points, faces) # Save the solution 
  FAS.resetCells(Cells)
  h = [sol[end][5*i-4] for i in eachindex(Cells)] 
  return LinearAlgebra.norm2(h)/sqrt(length(h)) ## Average thickness at t = 15.0 
end
# FINDING GRADIENT USING FINITE DIFFERENCE (Central Second order u' ≈ (u_{k+1} - u_{k-1})/2h)
p_backward = testDifferentiabilityInitialConditions([0.49998]) 
p_forward = testDifferentiabilityInitialConditions([0.50002])
finitediff = (p_forward - p_backward)/(0.50002 - 0.49998)
# FINDING GRADIENT USING AUTOMATIC DIFFERENTIATION (Accurate to machine precision) # 
autodiff = ForwardDiff.gradient(testDifferentiabilityInitialConditions, [0.50])
```

# Using custom rheology models

The default $\mu(I)$ rheology model used might not be suitable for all type of flows. The library allows for some customizations. All rheology models which have the basal stress term $\tau_b$ orthogonal to the flow velocity $\bar{u}$ are compatible, i.e. all models having $\tau_b \cdot \bar{u} = 0$ can be used. In empirical terms, the current implementation is valid for non-entraining models. 

For example, the following model (Vollemy) as mentioned in @rauter2018gmd: 

$$
\tau_b = \mu\;p_b\;\frac{\bar{u}}{\bar{u} + u_0} + \frac{\rho g}{\zeta}\lvert \bar{u}\rvert \bar{u}
$$

The library considers the basal friction term implicitly, and thus will need the coefficients in the implcit discretization, i.e. if 

$$ 
\tau_b = \mathcal{A}\bar{u}
$$, 

then write a function to return the coefficient $\mathcal{A}$. The function should also have a fixed signature: 

```julia
function myBasalStress(Cell, h, vel, pb, alpha, zeta, rho)
```

The variables `h`, `vel` and `pb` represent the value of the variables at any face. `alpha`, `zeta` and `rho` are the model parameters and `Cell` is a datastructure which contains geometrical information of the face if required. 

The following is a sample function which represents the model shown above. It uses the values for variables: 

$$
\mu = 0.38, u_0 = 10^{-7}, \zeta = 10^{4}, g = 9.81
$$ 

```julia
import LinearAlgebra
function Vollemy(Cell, h, vel, pb, alpha, zeta, rho)
    vel_mag = LinearAlgebra.norm2(vel)
    vel_inv = 1.0/(vel_mag + 1e-7)
    xi_inv = 1.0/(10000.0) # 1/xi
    return vel_inv*pb*0.38 + rho*9.81*xi_inv*vel_mag 
end
```

Once that's done, define the `Solution` object as: 

```julia
solution = FAS.Solution(
  <something>,
  basal_stress = Vollemy,
  <something>
)
```

and run the simulation as before! To perform differential calculations, wrap it inside a function. For example, to compute derivatives w.r.t. the parameter $\zeta$, define 

```julia
import LinearAlgebra
function testDifferentiability(x)
<somethings> 

function Vollemy(Cell, h, vel, pb, alpha, zeta, rho)
    vel_mag = LinearAlgebra.norm2(vel)
    vel_inv = 1.0/(vel_mag + 1e-7)
    # xi_inv = 1.0/(10000.0) # 1/xi
    xi_inv = 1.0/x[1]
    return vel_inv*pb*0.38 + rho*9.81*xi_inv*vel_mag 
end

solution = FAS.Solution(
  <something> 
  basal_stress = Vollemy
  <something> 
)

solver = FAS.Solver(solution)

<SIMULATION>...
end
```

and then call the related `ForwardDiff` function as above. 
