# Parser to parse "points", "faces", and "facelabels" files generated by OpenFOAM

#=
The PARSER Submodule is responsible for parsing files generated by OpenFOAM's meshing tool: PolyMesh. 
Parses text files containing vertices, face and face-indices information. The I/O is not multi-threaded beacuse
it is sequential. However, all processing after the disk read is multi-threaded.

Last Updated On: 14th January, 2025 18:36 UTC+5:30
=#

include("./src/parsepoints.jl")
include("./src/parsefaces.jl")
include("./src/parsefacelabels.jl")

export parsemesh

"""
    parsemesh(location_points::String, location_faces::String, location_faceLabels::String)
Parse the files of a mesh in OpenFoam format.
See also [`parsepoints`](@ref), [`parsefaces`](@ref), [`parsefacelabels`](@ref)
    
- location_points::String - Location of "points" file generated by OpenFOAM polymesh. 
- location_faces::String - Location of "faces" file generated by OpenFOAM polymesh.
This is an internal function and should not be exposed to the user.
"""
function parsemesh(location_points::String, location_faces::String, location_faceLabels::String)
    global FLOAT_TYPE, INT_TYPE, threads, stats
    stats && println("Using ", Threads.nthreads(), " threads")
    mesh_points = parsepoints(location_points)
    mesh_faces, corr_factor = parsefaces(location_faces) # Correction Factor, dev fix, don't change!
    idx_faces = parsefacelabels(location_faceLabels, corr_factor)
    surface_aligned_faces = deepcopy(mesh_faces[idx_faces])

    # Get points on the surface
    @inbounds surface_points_idx = [x[j] for x in surface_aligned_faces for j in eachindex(x)] # Get points on the surface aligned mesh
    unique!(surface_points_idx) # Remove repeated indcies
    sort!(surface_points_idx) # Sort the indices, prepare for remapping

    # Remapping of surface points in 1:N
    global_surface_idx_map = Dict(surface_points_idx .=> 1:length(surface_points_idx)) # New Index ReMap
    surface_aligned_faces_remapped = Vector{Vector{INT_TYPE[]}}(undef, length(surface_aligned_faces))
    @inbounds surface_points = mesh_points[surface_points_idx]

    @inbounds @maybe_threads Threads.nthreads == 1 || !threads for i in eachindex(surface_aligned_faces)
        l = length(surface_aligned_faces[i])
        surface_aligned_faces_remapped[i] = [global_surface_idx_map[j] for j in surface_aligned_faces[i]]
    end
    return surface_points, surface_aligned_faces_remapped
end
