#=
# Parser to parse the OpenFOAM meshfiles.
# Copyright (c) 2025 Tanish Jain.
# Licensed under the MIT license 
=#
include("./OpenFOAM/parsepoints.jl")
include("./OpenFOAM/parsefaces.jl")
include("./OpenFOAM/parsefacelabels.jl")

"""
    _parsemesh(location_points, location_faces, location_faceLabels)
Parse the files of a mesh in OpenFoam format.
    
- location_points::String - Location of "points" file generated by OpenFOAM polymesh. 
- location_faces::String - Location of "faces" file generated by OpenFOAM polymesh.
- location_faceLabels::String - Location of "facelabels" file generated by OpenFOAM polymesh.
"""
function _parsemesh(location_points::String, location_faces::String, location_faceLabels::String)
    STATS[] && println("Using ", Threads.nthreads(), " threads")
    points = _parsepoints_openfoam(location_points)
    tfaces, correction_factor = _parsefaces_openfoam(location_faces) # Correction Factor, dev fix, don't change!
    facelabels = _parsefacelabels_openfoam(location_faceLabels, correction_factor)
    faces = deepcopy(tfaces[facelabels])

    # Get points on the surface
    @inbounds points_idx = [x[j] for x in faces for j in eachindex(x)]
    unique!(points_idx)
    sort!(points_idx)

    # Remapping of surface points in 1:N
    global_surface_idx_map = Dict(points_idx .=> 1:length(points_idx))
    faces_remapped = Vector{Vector{INT_TYPE[]}}(undef, length(faces))
    @inbounds points_remapped = points[points_idx]

    @inbounds @maybe_threads Threads.nthreads == 1 || !THREADS[] for i in eachindex(faces)
        l = length(faces[i])
        faces_remapped[i] = [global_surface_idx_map[j] for j in faces[i]]
    end
    return points_remapped, faces_remapped
end
