# Parser to parse "points", "faces", and "facelabels" files generated by OpenFOAM 

#=
The PARSER Submodule is responsible for parsing files generated by OpenFOAM's meshing tool: PolyMesh. 
Parses text files containing vertices, face and face-indices information.

Last Updated On: 11th January, 2025 20:36 UTC+5:30
=#

include("./src/parsepoints.jl")
include("./src/parsefaces.jl")
include("./src/parsefacelabels.jl")