---
title: "API"
engine: tex 

execute:
  freeze: auto
---

**THIS IS STILL IN PROGRESS**

<em> A non-exhaustive list of all functions present in the library </em> 

Note that the acronym "**FAS**" expands to "**FASolverAvalanche**" 

# For external use (for users)

**Initialization** 

:::{.callout-note collapse="true"}
## FAS.Process 

```julia
struct Process 
        threads::Bool
        stats::Bool
        plots::Bool
        FLOAT_TYPE::DataType 
        INT_TYPE::DataType 
end
```
Contains user-defined choices for controlling a process. 

- threads - If set `true`, will use multiple threads equal to the number set in `JULIA_NUM_THREADS`. Default is `true`.
- stats - If set `true`, will display progress or solution intermediates (residuals, total dry cells, etc.). Default is `true`
- plots - If set `true`, initialize PyPlot backend. Default is `false`
- FLOAT_TYPE - Default type used for all floating point numbers throughout the library. Defaults to `Float64`. Any other type is not yet supported. 
- INT_TYPE - Default type used for all integers throughout the library. Defaults to `Int64`
"""
:::

:::{.callout-note collapse="true"}
## FAS.init(process)

```julia
init(process::Process)
```
Initialize the library and start PyPlot backend if `process.plots=true`

- process::Process - `Process` object containing computation choices. 
:::

**Mesh Parsing**

:::{.callout-note collapse="true"}
## FAS.parsemesh(location_points, location_faces, location_faceLabels)

Parse and reorder based on "faceLabels" the data extracted from "points" and "faces".
:::

# Internal functions (for developers)

**Mesh Parsing**

:::{.callout-note collapse="true"}
## FAS.parsepoints(location_points)

```julia
parsepoints(location_points::String)
```
Parse the points file generated in an OpenFoam format and stores the coordinates in `FLOAT_TYPE` format. 

- location_points::String - Location of the "points" file generated by OpenFOAM avalanche module.
:::

:::{.callout-note collapse="true"}
## FAS.parsefaces(location_faces)

```julia
parsefaces(location_faces::String)
```
Parse the connectivity list of a mesh in an OpenFOAM format and store it in type `INT_TYPE`

- location_faces::String - Location of the "faces" file generated by OpenFOAM avalanche module.
:::

:::{.callout-note collapse="true"}
## FAS.parsefacelabels(location_faceLabels, correction_factor)

```julia
parsefacelabels(location_faceLabels::String, correction_factor)
```
Parse indices of faces forming the terrain in a text file with OpenFoam format and stores it in `INT_TYPE`

- location_faceLabels::String
- correction_factor::INT_TYPE - To account for the corrections in the text file (where the parser skipped because of invalid syntax)
:::