using GlissADe

## HOW TO RUN THIS FILE? ##
# From the project root: julia --project examples/wolfsgrube_mountain/wolfsgrube_mountain.jl

## What does this file do? ##
# This will simulate the avalanche over the wolfsgrube mountain case for a duration of 750 seconds.

init(threads = true, stats = false, plots = false, float_type = Float64, int_type = Int64) # Initialize the library

# Parse the mesh generated by OpenFOAM's polyMesh and makeFaMesh with ASCII files available at this locations.
points, faces = parsemesh(
    "./examples/wolfsgrube_mountain/wolfsgrube_mountain/points",
    "./examples/wolfsgrube_mountain/wolfsgrube_mountain/faces",
    "./examples/wolfsgrube_mountain/wolfsgrube_mountain/faceLabels",
)
Cells = preprocess(points, faces, Float64, comp_neighbours = true) # Precompute geometrical information.
# If comp_neighbours=true, neighbours will be recomputed even if already stored.

# Check Sparsity pattern of implicit matrix (after reordering) #
neighbours = [Cell.neighbours for Cell in Cells]
A = GlissADe.adjMatrix(neighbours) # internal helper, not exported
##

# Set up release area
meshbounds(Cells) # Find the span of the mesh.

# Define the region in which a regular polygon is to be found: [xMin, xMax, yMin, yMax].
# npoints are the number of edges in the polygon.
polygon = findRegularPolygon([1300.0, 1500.0, 0.0, 500.0], npoints = 6)
cells_inside = cellsInsideBoundingPolygon(polygon, Cells) # Find the faces lying inside the region defined.
initializeGeometry(cells_inside, Cells, 1500.0, h0 = 1.5, u0 = [0.0, 0.0, 0.0]) # Initialize the faces inside the region.

# Define Parameters and simulation settings.
solution = Solution(
    alpha = 0.5, # Coefficient for pressure terms
    zeta = 1.0, # Coefficient for momentum terms
    rho = 1500.0, # Material density
    alpha_p = 0.4, # Under relaxation for pressure.
    alpha_u = 0.4,  # Under relaxation for velocity
    alpha_h = 0.4,  # Under relaxation for thickness.
    p_MAX_RESIDUAL = 1e-4, # Maximum allowed residual for pressure constraint.
    h_MAX_RESIDUAL = 5e-1, # Maximum allowed residual for thickness equation.
    u_MAX_RESIDUAL = 5e-1, # Maximum allowed residual for momentum equation.
    MAX_ITERS = 35, # Maximum Iterations per timestep.
    MIN_ITERS = 30, # Minimum iterations per timestep.
    h_clip = 0.0, # Clip the thickness to 0 if h < h_clip
    h_min = 1e-3, # Minimum height to be considered wet.
    Cells = Cells, # Precomputed geometry and initial conditions
    location = "./solution", # Folder to store the intermediate VTK files. Only formats with "./{name}" are allowed at present.
    points = points,  # Vertices of the mesh
    faces = faces, # Connectivity list of the mesh
)
solver = Solver(solution) # Construct Solver object
time_steps, sol = solve(solver, (0.0, 750.0), saveat = 0.5, Cₘ = 0.13) # SIMULATE!
writeToVTK(solution.location, sol, points, faces) # Write the solution to VTK. Smoothens the intermediates to get accurate solutions.
resetCells(Cells) # Reset all cells to 0 thickness and velocity.
