import FASolverAvalanche as FAS  

## How to run this file? ## 
# Ensure that the working directory "pwd" is "<something>/internship-tj, the project's root. 
# Run from terminal: "julia --project -t <num_threads> ./examples/simpleslope/simpleslope.jl"
# Or Run from REPL as usual. If file not found error occurs check if the file paths are correct. 

## What does this code do? ## 
# This will simulate the avalanche on a simpleslope geometry for the duration of 30 seconds. 

# Defines how a simulation process should be run. 
process = FAS.Process(
            threads = true, 
            stats = true,
            plots = false,
            implicit = true,  
            INT_TYPE = Int64
)
FAS.init(process) # Initialize the library 

# Parse the mesh generated by OpenFOAM's polyMesh and makeFaMesh with ASCII files available at this locations. 
points, faces = FAS.parsemesh("./examples/simpleslope/simpleslope/points", "./examples/simpleslope/simpleslope/faces", 
                                "./examples/simpleslope/simpleslope/faceLabels")
Cells = FAS.preprocess(points, faces, Float64, comp_neighbours=true) # Precompute geometrical information. 
# If comp_neighbours=true, neighbours will be recomputed even if already stored. 

# Check Sparsity pattern of implicit matrix (after reordering) #
# neighbours = [Cell.neighbours for Cell in Cells]
# A = FAS.adjMatrix(neighbours) # Use spy(A) or similar functions to see reordered sparse matrix. 
##

# Set up release area 
# FAS.meshbounds(Cells) # Find the span of the mesh

# Define the region in which a regular polygon is to be found: [xMin, xMax, yMin, yMax]. 
# npoints are the number of edges in the polygon.
polygon = FAS.findRegularPolygon([5.0, 10.0, -6.0,6.0], npoints=6) # Example Release conditions. 
cells_inside = FAS.cellsInsideBoundingPolygon(polygon, Cells) # Find the faces lying inside the region defined. 

# Using rho = 1500.0 
FAS.initializeGeometry(cells_inside, Cells, 1500.0, h0 = 0.2, u0 = [0.0,0.0,0.0]) # Initialize the faces inside the region. 

# Define Parameters and simulation settings. 
solution = FAS.Solution(
    alpha = 0.5, # Coefficient for pressure terms
    zeta = 1.25, # Coefficient for momentum terms 
    rho = 1500.0, # Material density 
    alpha_p = 0.5, # Under relaxation for pressure. 
    alpha_u = 0.5,  # Under relaxation for velocity
    alpha_h = 0.5,  # Under relaxation for thickness.
    p_MAX_RESIDUAL = 1e-5, # Maximum allowed residual for pressure constraint. 
    h_MAX_RESIDUAL = 5e-1, # Maximum allowed residual for thickness equation. 
    u_MAX_RESIDUAL = 5e-1, # Maximum allowed residual for momentum equation. 
    MAX_ITERS = 250, # Maximum Iterations per timestep. 
    MIN_ITERS = 200, # Minimum iterations per timestep. 
    h_clip = 0.0, # Clip the thickness to 0 if h < h_clip
    h_min = 1e-3, # Minimum height to be considered wet. 
    Cells = Cells, # Precomputed geometry and initial conditions
    location = "./solution", # Folder to store the intermediate VTK files. Only formats with "./{name}" are allowed at present. 
    points = points,  # Vertices of the mesh
    faces = faces # Connectivity list of the mesh 
)
solver = FAS.Solver(solution) # Construct Solver object (0.9)
time_steps, sol = FAS.solve(solver, (0.0,30.0),saveat=0.2,Cₘ=4.5, rtol = 1e-4) # SIMULATE!
FAS.writeToVTK(solution.location, sol, points, faces) # Write the solution to VTK. Smoothens the intermediates to get accurate solutions. 
FAS.resetCells(Cells) # Reset all cells to 0 thickness and velocity. 