import FASolverAvalanche as FAS

## How to run this file? ##
# Ensure that the working directory "pwd" is "<something>/internship-tj, the project's root.
# Run from terminal: "julia --project -t <num_threads> ./examples/simpleslope/simpleslope.jl"
# Or Run from REPL as usual. If file not found error occurs check if the file paths are correct.

## What does this code do? ##
# This will simulate the avalanche on a simpleslope geometry for the duration of 30 seconds.

FAS.init(
    plots = false,
    threads = true,
    stats = true,
    float_type = Float64,
    int_type = Int64
) # Initialize the library

# Parse the mesh generated by OpenFOAM's polyMesh and makeFaMesh with ASCII files available at this locations.
points, faces = FAS._parsemesh(
    "./examples/simpleslope/simpleslope/points", "./examples/simpleslope/simpleslope/faces",
    "./examples/simpleslope/simpleslope/faceLabels"
)
Cells = FAS.preprocess(points, faces, Float64, comp_neighbours = true) # Precompute geometrical information.
#
