#=
# Parses the faces in OpenFOAM generated meshfiles.
# Copyright (c) 2025 Tanish Jain.
# Licensed under the MIT license.
=#
"""
    _parsefaces_openfoam(location_faces)
Parse the connectivity list of a mesh in an OpenFOAM format and store it in type `INT_TYPE`

## Arguments
- `location_faces::String` - Location of the "faces" file generated by OpenFOAM avalanche module
"""
function _parsefaces_openfoam(location_faces::String)
    s_faces_file = open(location_faces, "r") do f_faces
        readlines(f_faces)
    end
    n_faces = parse(INT_TYPE[], s_faces_file[20])
    ts_faces = @view s_faces_file[22:(22+n_faces-1)]
    s_faces = String[]
    for (idx, face) in enumerate(ts_faces)
        !_check_valid_face(face) && continue
        push!(s_faces, face)
    end

    STATS[] && println("Reading face information...")
    faces = Vector{Vector{INT_TYPE[]}}(undef, length(s_faces))
    @inbounds @maybe_threads Threads.nthreads == 1 || !THREADS[] for i in eachindex(s_faces)
        line = s_faces[i]
        parts = split(line, '(')
        # n = parse(INT_TYPE[], strip(parts[1]))  # Number of points in the face Check: Length(numbers) == n. Not required, In Openfoam we trust!
        numbers_str = strip(parts[2], [' ', ')'])  # Remove Trailing Parenthesis
        numbers = split(numbers_str, " ")
        faces[i] = parse.(INT_TYPE[], numbers) .+ 1  # Convert to 1-based indexing
    end
    return faces, INT_TYPE[](length(faces) - n_faces) # Vector{faces}, correction_factor
end
