#=
# Parser to parse points (3D coordinates) in OpenFOAM meshfiles.
# Copyright (c) 2025 Tanish Jain
# Licensed for use under MIT License
=#
"""
            _parsepoints_openfoam(location_points)
Parse the points file generated in an OpenFoam format and stores the coordinates in `FLOAT_TYPE` format.

## Arguments
- location_points::String - Location of the "points" file generated by OpenFOAM avalanche module
"""
function _parsepoints_openfoam(location_points::String)
    s_points_file = open(location_points, "r") do f_points
        readlines(f_points)
    end

    n_points = parse(INT_TYPE[], s_points_file[20])
    s_points = @view s_points_file[22:(22+n_points-1)]

    STATS[] && println("Reading point cloud...")
    points = Vector{Vector{FLOAT_TYPE[]}}(undef, length(s_points))
    @inbounds @maybe_threads Threads.nthreads() == 1 || !THREADS[] for i in
                                                                     eachindex(s_points)
        s = split(strip(s_points[i], ('(', ')')))
        points[i] = [
            parse(FLOAT_TYPE[], s[1]),
            parse(FLOAT_TYPE[], s[2]),
            parse(FLOAT_TYPE[], s[3]),
        ] # always of appropriate size
    end
    return points
end
