# File parser to parse "points", "faces" and "faceLabels" files generated by OpenFOAM

export parsepoints, parsefaces, parsefacelabels

"""
            parsepoints(location_points::String)
Parse the points file generated in an OpenFoam format and stores the coordinates in `FLOAT_TYPE` format. 
See also: [`parsefaces`](@ref), [`parsefacelabels`](@ref), [`parsemesh`](@ref)

## Arguments 
- location_points::String - Location of the "points" file generated by OpenFOAM avalanche module
""" 
function parsepoints(location_points::String)

    ## GET GLOBAL VARIABLES ## 
    global FLOAT_TYPE, INT_TYPE, threads, stats
    
    # Read file 
    f_point_cloud = open(location_points, "r")
    s_points_file = split(read(f_point_cloud, String), '\n')
    close(f_point_cloud)

    # [Advice on Stack] Only use Regex if you have to! 
    total_points = parse(INT_TYPE[], s_points_file[20])
    s_points_cloud = @view s_points_file[22:22+total_points-1]

    # Process the string
    stats && println("Reading point cloud...")
    mesh_points = Vector{Vector{FLOAT_TYPE[]}}(undef, length(s_points_cloud)) # Preallocating for speed 
    @inbounds @maybe_threads Threads.nthreads == 1 || !threads for i in eachindex(s_points_cloud) 
            s = split(strip(s_points_cloud[i], ('(', ')')))
            mesh_points[i] = [parse(FLOAT_TYPE[], s[1]),parse(FLOAT_TYPE[], s[2]), parse(FLOAT_TYPE[], s[3])] # always of appropriate size
    end
    return mesh_points 
end

"""
`INTERNAL`
Auxillary for [`parsefaces`](@ref)
"""
function is_valid_integer(s)
    global INT_TYPE
    try
        parse(INT_TYPE[], s)
        return true
    catch
        return false
    end
end

"""
`INTERNAL`. Auxillary for [`parsefaces`](@ref)
"""
function is_valid_face_line(line)
    parts = split(line, '(', limit=2)
    length(parts) != 2 && return false 
    @inbounds n_str = strip(parts[1])
    !is_valid_integer(n_str) && return false 
    n = parse(INT_TYPE[], n_str)
    @inbounds face_str = strip(parts[2], [' ', ')'])
    face_elements = split(face_str)
    length(face_elements) != n && return false 
    !all(is_valid_integer, face_elements) && return false 
    return true
end



"""
    parsefaces(location_faces::String)
Parse the connectivity list of a mesh in an OpenFOAM format and store it in type `INT_TYPE`
See also: [`parsepoints`](@ref), [`parsefacelabels`](@ref), [`parsemesh`](@ref)

## Arguments 
- location_faces::String - Location of the "faces" file generated by OpenFOAM avalanche module
"""
function parsefaces(location_faces::String)
    global INT_TYPE, stats, threads

    # Read file line by line
    total_faces = 0
    s_faces_arr = String[]

    open(location_faces, "r") do f_faces
        for (i, line) in enumerate(eachline(f_faces)) 
            if i == 20
                total_faces = parse(INT_TYPE[], line)
            elseif i >= 22 
                !is_valid_face_line(line) && continue 
                push!(s_faces_arr, line)
            end
        end
    end
    # Process the string
    stats && println("Reading face information...")
    mesh_faces = Vector{Vector{INT_TYPE[]}}(undef, length(s_faces_arr))
    @inbounds @maybe_threads Threads.nthreads() ==1 || !threads for i in eachindex(s_faces_arr)
        line = s_faces_arr[i]
        parts = split(line, '(')
        # n = parse(Int, strip(parts[1]))  # Number of points in the face Check: Length(numbers) == n. Not required, In Openfoam we trust!
        numbers_str = strip(parts[2], [' ', ')'])  # Remove Trailing Parenthesis
        numbers = split(numbers_str, " ")
        mesh_faces[i] = parse.(INT_TYPE[], numbers) .+ 1  # Convert to 1-based indexing
    end
    return mesh_faces, INT_TYPE[](length(mesh_faces) - total_faces)
end

"""
    parsefacelabels(location_faceLabels::String, correction_factor)
Parse indices of the faces forming the terrain in a text file with OpenFoam format and stores it in `INT_TYPE`
See also: [`parsepoints`](@ref), [`parsefaces`](@ref), [`parsemesh`](@ref)

## Arguments 
- location_faceLabels::String
- correction_factor::INT_TYPE - To account for the corrections in the text file (where the parser skipped because of invalid syntax)
"""
function parsefacelabels(location_faceLabels::String, correction_factor)
    global INT_TYPE, threads, stats

    # Open file and skip header lines directly
    f_surface_aligned_faces = open(location_faceLabels, "r")
    for _ in 1:19
        readline(f_surface_aligned_faces)
    end

    total_surface_aligned_faces = parse(INT_TYPE[], readline(f_surface_aligned_faces))
    idx_surface_aligned_faces = Vector{INT_TYPE[]}(undef, total_surface_aligned_faces) # Preallocating for speed
    readline(f_surface_aligned_faces) # Opening parenthesis
    # Read and parse face labels
    stats && println("Reading face labels...")
    s_surface_aligned_faces_arr = Vector{String}(undef, total_surface_aligned_faces)
    @inbounds for i in 1:total_surface_aligned_faces
        s_surface_aligned_faces_arr[i] = readline(f_surface_aligned_faces)
    end
    close(f_surface_aligned_faces)

    @inbounds @maybe_threads Threads.nthreads() == 1 || !threads for i in 1:total_surface_aligned_faces
        idx_surface_aligned_faces[i] = parse(INT_TYPE[], s_surface_aligned_faces_arr[i]) + 1 + correction_factor
    end
    return idx_surface_aligned_faces
end

